// Mock item list

export const mockItems = [
  { store: 'Rhybox', name: 'Puree - Strawberry', price: 84.17 },
  { store: 'InnoZ', name: 'Puree - Raspberry', price: 61.98 },
  { store: 'Avaveo', name: 'Flower - Leather Leaf Fern', price: 82.79 },
  { store: 'Zoozzy', name: 'Muffin Carrot - Individual', price: 13.66 },
  { store: 'Skyvu', name: 'Leeks - Baby, White', price: 73.67 },
  { store: 'Rhybox', name: 'Wine - Barbera Alba Doc 2001', price: 19.33 },
  { store: 'Muxo', name: 'Fish - Bones', price: 40.31 },
  { store: 'Edgeclub', name: 'Poppy Seed', price: 49.43 },
  { store: 'Meezzy', name: 'Gelatine Powder', price: 96.16 },
  { store: 'Chatterpoint', name: 'Beer - Original Organic Lager', price: 82.56 },
  { store: 'Quatz', name: 'Onions - Vidalia', price: 94.7 },
  { store: 'Flipstorm', name: 'Gherkin', price: 48.62 },
  { store: 'Kamba', name: 'Oranges', price: 12.5 },
  { store: 'Ooba', name: 'Pasta - Linguini, Dry', price: 86.68 },
  { store: 'Einti', name: 'Duck - Breast', price: 85.99 },
  { store: 'Blognation', name: 'Apron', price: 9.43 },
  { store: 'Blogspan', name: 'Pastry - Chocolate Chip Muffin', price: 52.77 },
  { store: 'Gigaclub', name: 'Mushroom - Morels, Dry', price: 95.36 },
  { store: 'Kwimbee', name: 'Appetizer - Sausage Rolls', price: 83.28 },
  { store: 'Kimia', name: 'Steel Wool', price: 90.56 },
  { store: 'Thoughtsphere', name: 'Sour Cream', price: 96.39 },
  { store: 'Rhyloo', name: 'Nantucket Pine Orangebanana', price: 95.69 },
  { store: 'Brightdog', name: 'Foam Cup 6 Oz', price: 77.97 },
  { store: 'Twimbo', name: 'Vodka - Lemon, Absolut', price: 54.95 },
  { store: 'Youbridge', name: 'Beans - Soya Bean', price: 78.89 },
  { store: 'Blognation', name: 'Shrimp - 31/40', price: 25.94 },
  { store: 'Twinte', name: 'Sprouts Dikon', price: 8.53 },
  { store: 'Blogpad', name: 'Star Fruit', price: 39.66 },
  { store: 'Tekfly', name: 'Mix Pina Colada', price: 5.79 },
  { store: 'Topdrive', name: 'Hagen Daza - Dk Choocolate', price: 52.26 },
  { store: 'Geba', name: 'Cherries - Bing, Canned', price: 28 },
  { store: 'Feedfire', name: 'Squash - Butternut', price: 45.65 },
  { store: 'Voonder', name: 'Rabbit - Saddles', price: 41.03 },
  { store: 'Einti', name: 'Wine - Sicilia Igt Nero Avola', price: 36.25 },
  { store: 'Dynazzy', name: 'Wine - Cava Aria Estate Brut', price: 25.03 },
  { store: 'Jatri', name: 'Curry Powder Madras', price: 48.5 },
  { store: 'Twitterbeat', name: 'Icecream - Dibs', price: 13.05 },
  { store: 'Midel', name: 'Juice - Grape, White', price: 32.26 },
  { store: 'Ailane', name: 'Truffle - Whole Black Peeled', price: 58.09 },
  { store: 'Flashspan', name: 'Bread - French Baquette', price: 94.29 },
  { store: 'Voomm', name: 'Onions - Cippolini', price: 6.09 },
  { store: 'Midel', name: 'Lemonade - Black Cherry, 591 Ml', price: 29.34 },
  { store: 'Jetwire', name: 'Beef Flat Iron Steak', price: 37.17 },
  { store: 'Blognation', name: 'Sauce - Soya, Dark', price: 56.82 },
  { store: 'Yabox', name: 'Soup - Campbells Asian Noodle', price: 66.93 },
  { store: 'Demizz', name: 'Salmon - Atlantic, No Skin', price: 77.36 },
  { store: 'Twimm', name: 'Rice - Jasmine Sented', price: 56.37 },
  { store: 'Topicshots', name: 'Mussels - Frozen', price: 7.81 },
  { store: 'Rhybox', name: 'Pastry - Mini French Pastries', price: 99.54 },
  { store: 'Yozio', name: 'Fish - Base, Bouillion', price: 10.87 },
  { store: 'Zoombeat', name: 'Beef - Ox Tongue, Pickled', price: 36.03 },
  { store: 'Babbleset', name: 'Mousse - Passion Fruit', price: 89.86 },
  { store: 'Leexo', name: 'Beef - Bones, Marrow', price: 62.85 },
  { store: 'Ooba', name: 'Tart - Lemon', price: 21.45 },
  { store: 'Voomm', name: 'Five Alive Citrus', price: 39.96 },
  { store: 'Abata', name: 'Wine - Red, Mosaic Zweigelt', price: 70.85 },
  { store: 'Jabbercube', name: 'Chicken Breast Halal', price: 31.69 },
  { store: 'Dabtype', name: 'Veal - Insides Provini', price: 26.74 },
  { store: 'Rhybox', name: 'Nut - Almond, Blanched, Sliced', price: 73.02 },
  { store: 'Kwinu', name: 'Oil - Sunflower', price: 14.21 },
  { store: 'Jatri', name: 'Lid - 3oz Med Rec', price: 23.9 },
  { store: 'Bluezoom', name: 'Pepper - Red Chili', price: 89.34 },
  { store: 'Skidoo', name: 'Cognac - Courvaisier', price: 80.38 },
  { store: 'Brainsphere', name: 'Pasta - Canelloni, Single Serve', price: 34.44 },
  { store: 'Skimia', name: 'Soy Protein', price: 78.07 },
  { store: 'Realcube', name: 'Graham Cracker Mix', price: 34.09 },
  { store: 'Wordtune', name: 'Pasta - Penne, Rigate, Dry', price: 23.89 },
  { store: 'Yotz', name: 'Munchies Honey Sweet Trail Mix', price: 72.37 },
  { store: 'Yakijo', name: 'Longos - Greek Salad', price: 85.11 },
  { store: 'InnoZ', name: 'Turkey - Whole, Fresh', price: 37.26 },
  { store: 'Quimm', name: 'Pastry - Chocolate Marble Tea', price: 30.65 },
  { store: 'Riffwire', name: 'Milk - 2%', price: 35.42 },
  { store: 'Browsecat', name: 'Calypso - Pineapple Passion', price: 18.14 },
  { store: 'Feedfish', name: 'Kellogs Cereal In A Cup', price: 43.12 },
  { store: 'Reallinks', name: 'Cranberry Foccacia', price: 30.73 },
  { store: 'Muxo', name: 'Muffin - Mix - Mango Sour Cherry', price: 44.18 },
  { store: 'Feedfire', name: 'Melon - Watermelon Yellow', price: 61.04 },
  { store: 'Roomm', name: 'Containter - 3oz Microwave Rect.', price: 48.82 },
  { store: 'Mymm', name: 'Table Cloth 53x69 White', price: 48.14 },
  { store: 'Jabberstorm', name: 'Cheese - Shred Cheddar / Mozza', price: 44.56 },
  { store: 'Thoughtblab', name: 'Marzipan 50/50', price: 87.72 },
  { store: 'Eimbee', name: 'Shiro Miso', price: 74.44 },
  { store: 'Twitterlist', name: 'Daikon Radish', price: 66.62 },
  { store: 'Livepath', name: 'Beer - Camerons Cream Ale', price: 66.75 },
  { store: 'Twitterbeat', name: 'Pork - Tenderloin, Fresh', price: 23.13 },
  { store: 'Yata', name: 'Wine - Alicanca Vinho Verde', price: 32.95 },
  { store: 'Viva', name: 'Hold Up Tool Storage Rack', price: 82.34 },
  { store: 'Oyondu', name: 'Soup - Campbells', price: 50.52 },
  { store: 'Camido', name: 'Mushroom - Porcini, Dry', price: 61.73 },
  { store: 'Izio', name: 'Beets - Candy Cane, Organic', price: 45.96 },
  { store: 'Divavu', name: 'Pepper - Green', price: 21.41 },
  { store: 'Bubbletube', name: 'English Muffin', price: 14.7 },
  { store: 'Edgetag', name: 'Coffee Cup 8oz 5338cd', price: 39.31 },
  { store: 'Jetpulse', name: 'Neckerchief Blck', price: 95.97 },
  { store: 'Vipe', name: 'Veal - Striploin', price: 80 },
  { store: 'Vidoo', name: 'Zucchini - Mini, Green', price: 5.11 },
  { store: 'Bubblebox', name: 'Potatoes - Yukon Gold, 80 Ct', price: 31.86 },
  { store: 'Voonder', name: 'Ecolab Crystal Fusion', price: 43.9 },
  { store: 'Kare', name: 'Soda Water - Club Soda, 355 Ml', price: 6.97 },
  { store: 'Bluezoom', name: 'Wine - Casillero Del Diablo', price: 57.24 },
];
